name: altinay_stajyer_ocr
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2

  google_ml_kit: ^0.16.1
  permission_handler: ^10.4.3
  camera: ^0.10.5+2


  image_picker: ^1.0.2
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0

  http: ^0.13.6


  image_cropper: ^4.0.1
  intl: ^0.18.1
  image: ^4.0.17
  typed_data: ^1.3.2
  url_launcher: ^6.1.12
  file_picker: ^5.3.3

  firebase_storage: ^11.2.6






dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/altinay.png




  uses-material-design: true































